### ISSUE TITLE
"An unexpected error occurred trying to execute that command"

### ISSUE THREAD

**Issue by GaryLoop** [North-West-Wind/FabricSurvivalSpectator#1]
It seems the /s command is unrecognized. 

- New single player Survival world (assumed support because "Installing it on client-side will allow this feature to be used in singleplayer only.")
- Cheats off
- Minecraft version 1.17 (fabric-loader-0.11.3-1.17/fabric/Fabric)

Expected Outcome: 
- /s toggles game state between survival and spectator

**Comment by North-West-Wind** [comment]
Fixed in 2.0.1
